apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-three
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-three-pod
  template:
    metadata:
      labels:
        app: app-three-pod
    spec:
      containers:
        - name: app-three-container
          image: arthurprnt/hello-k8s:latest
          env:
            - name: MESSAGE
              value: "Hello from app3"
          ports:
            - containerPort: 8080