apiVersion: apps/v1  # API pour les objets de type Deployment
kind: Deployment
metadata:
  name: app                     # Nom unique du déploiement                
spec:
  replicas: 1                      # 🧬 Nombre de copies (pods) de l'app à maintenir
  selector:
    matchLabels:
      app: app-pod                  # 🔗 Lien entre le deployment et les pods qu’il gère
  template:
    metadata:
      labels:
        app: app-pod                # Ces labels seront appliqués aux pods créés
    spec:
      containers:
        - name: app-container
          image: wil42/playground:v1        # 🔧 Image Docker à lancer dans ce pod
          ports:
            - containerPort: 8080    # Port exposé à l'intérieur du pod