Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.define "gitlab" do |s|
    s.vm.network "private_network", ip: "192.168.56.110"
    s.vm.hostname = "gitlab"
    s.vm.provider "virtualbox" do |vb|
      vb.name = "gitlab"
      vb.memory = "1024"
      vb.cpus = 1
    end
    s.vm.provision "shell", path: "scripts/install-docker.sh"
    s.vm.provision "shell", path: "scripts/install-k3d.sh"
    s.vm.provision "shell", path: "scripts/install-kubectl.sh"
  end
end
